### ISSUE TITLE
Attributes cannot be expanded with tab

### ISSUE THREAD

**Issue by franciscolourenco** [agibsonsw/HTMLAttributes#4]
I'm trying to expand attributes with tab without displaying the popup list but it is not working.
Is this expected?

Thanks

**Comment by agibsonsw** [comment]
It works for me, and most others I believe, by typing 2 or 3 letters and pressing Tab, and I never see (or want to see) the popup list. It may take a few attempts for ST to learn your preferences. If necessary, press Ctrl-Space to produce the list, select your attribute; it should begin to learn this preference.

Otherwise, there may be another plug-in or setting that conflicts.

**Comment by franciscolourenco** [comment]
Do you have the Emmet plugin installed?

**Comment by agibsonsw** [comment]
Hello. No, I don't. You could use Package Control to temporarily disable Emmet. Re-start ST to see if this is conflicting.

**Comment by franciscolourenco** [comment]
Yes, it conflicts with Emmet.
Emmet doesn't provide attribute expansion, ST2 attribute autocomplete is broken, and this doesn't work with emmet installed.

**Comment by agibsonsw** [comment]
Yes, I suggested previously on the ST Forums that this possibly won't work well with Zen-coding/ Emmet; they are different approaches. Shame that it conflicts though - I'm a little surprised. If I get a chance over the weekend I'll try this out myself. If necessary, I'll update my readme to notify of the conflict.

Regards, Andy.
